/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppVehiclesRouteImport } from './routes/_authenticated/app.vehicles'
import { Route as AuthenticatedAppMyTripsRouteImport } from './routes/_authenticated/app.my-trips'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/app.maintenance'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/app.expenses'
import { Route as AuthenticatedAppDriversRouteImport } from './routes/_authenticated/app.drivers'
import { Route as AuthenticatedAppDispatchRouteImport } from './routes/_authenticated/app.dispatch'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppTripsNewRouteImport } from './routes/_authenticated/app.trips.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVehiclesRoute =
  AuthenticatedAppVehiclesRouteImport.update({
    id: '/app/vehicles',
    path: '/app/vehicles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMyTripsRoute = AuthenticatedAppMyTripsRouteImport.update({
  id: '/app/my-trips',
  path: '/app/my-trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/app/maintenance',
    path: '/app/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/app/expenses',
    path: '/app/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDriversRoute = AuthenticatedAppDriversRouteImport.update({
  id: '/app/drivers',
  path: '/app/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDispatchRoute =
  AuthenticatedAppDispatchRouteImport.update({
    id: '/app/dispatch',
    path: '/app/dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTripsNewRoute =
  AuthenticatedAppTripsNewRouteImport.update({
    id: '/app/trips/new',
    path: '/app/trips/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/app/drivers': typeof AuthenticatedAppDriversRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/my-trips': typeof AuthenticatedAppMyTripsRoute
  '/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/app/trips/new': typeof AuthenticatedAppTripsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/app/drivers': typeof AuthenticatedAppDriversRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/app/my-trips': typeof AuthenticatedAppMyTripsRoute
  '/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/app/trips/new': typeof AuthenticatedAppTripsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/_authenticated/app/drivers': typeof AuthenticatedAppDriversRoute
  '/_authenticated/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/_authenticated/app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/app/my-trips': typeof AuthenticatedAppMyTripsRoute
  '/_authenticated/app/vehicles': typeof AuthenticatedAppVehiclesRoute
  '/_authenticated/app/trips/new': typeof AuthenticatedAppTripsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/drivers'
    | '/app/expenses'
    | '/app/maintenance'
    | '/app/my-trips'
    | '/app/vehicles'
    | '/app/trips/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/dashboard'
    | '/app/dispatch'
    | '/app/drivers'
    | '/app/expenses'
    | '/app/maintenance'
    | '/app/my-trips'
    | '/app/vehicles'
    | '/app/trips/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/dispatch'
    | '/_authenticated/app/drivers'
    | '/_authenticated/app/expenses'
    | '/_authenticated/app/maintenance'
    | '/_authenticated/app/my-trips'
    | '/_authenticated/app/vehicles'
    | '/_authenticated/app/trips/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/vehicles': {
      id: '/_authenticated/app/vehicles'
      path: '/app/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AuthenticatedAppVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/my-trips': {
      id: '/_authenticated/app/my-trips'
      path: '/app/my-trips'
      fullPath: '/app/my-trips'
      preLoaderRoute: typeof AuthenticatedAppMyTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/maintenance': {
      id: '/_authenticated/app/maintenance'
      path: '/app/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/expenses': {
      id: '/_authenticated/app/expenses'
      path: '/app/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/drivers': {
      id: '/_authenticated/app/drivers'
      path: '/app/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AuthenticatedAppDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dispatch': {
      id: '/_authenticated/app/dispatch'
      path: '/app/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AuthenticatedAppDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/trips/new': {
      id: '/_authenticated/app/trips/new'
      path: '/app/trips/new'
      fullPath: '/app/trips/new'
      preLoaderRoute: typeof AuthenticatedAppTripsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDispatchRoute: typeof AuthenticatedAppDispatchRoute
  AuthenticatedAppDriversRoute: typeof AuthenticatedAppDriversRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppMyTripsRoute: typeof AuthenticatedAppMyTripsRoute
  AuthenticatedAppVehiclesRoute: typeof AuthenticatedAppVehiclesRoute
  AuthenticatedAppTripsNewRoute: typeof AuthenticatedAppTripsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDispatchRoute: AuthenticatedAppDispatchRoute,
  AuthenticatedAppDriversRoute: AuthenticatedAppDriversRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRoute,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppMyTripsRoute: AuthenticatedAppMyTripsRoute,
  AuthenticatedAppVehiclesRoute: AuthenticatedAppVehiclesRoute,
  AuthenticatedAppTripsNewRoute: AuthenticatedAppTripsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
